#!/usr/bin/env python3
"""Index every lower-fanout typed scalar without equating lexical reuse and policy."""

import collections
import gzip
import hashlib
import json
import re
import sys
from pathlib import Path


NUMBER_ROLES = {
    "shared_contract_candidate": {59, 73, 32003, 64000, 65000, 65536, 59999},
    "shared_mechanic_distinct_owner": {18, 25, 36, 150, 220, 250, 448, 493, 1000000, 1073741824, 1500, 2048},
    "http_or_system_protocol": {65, 201, 202, 204, 400, 405, 408, 409, 422, 503, 599, 65535},
    "source_role_mixed_or_independent": {
        0.5, 1.5, 11, 14, 15, 19, 22, 30, 34, 43, 44, 46, 48,
        63, 90, 92, 96, 99, 100.0, 115, 122, 123, 125, 126,
        150, 600, 900, 2000, 9999, 100000, 300000, 3600000,
    },
}

# These values are AST scalar leaves generated by Elixir syntax, not decimal
# policy literals in the source. Context is essential before claiming a bound.
SYNTAX_CODEPOINTS = {34, 44, 46, 48, 63, 90, 92, 97, 115, 122, 123, 125, 126}

REVIEWED_STRINGS = {
    "127.0.0.1": "loopback_protocol_distinct_bind_display_origin_roles",
    "openai-compatible-2026-08": "covered_by_telemetry-usage-32",
    "PRAGMA busy_timeout = ": "sqlite_syntax_distinct_timeout_policies",
    "cache_read_input_tokens": "provider_wire_alias_distinct_precedence",
}

FOUR_PLUS_TOPIC = {
    ".branch.push", "agent.phase.", "branch.push", "check_run", "check_suite",
    "issue_comment", "item/completed", "item/tool/call",
    "pull_request_review_comment", "ready_for_review", "turn/failed",
}
FOUR_PLUS_DISPLAY = {
    " attempts=", " elapsed_ms=", " request_id=", " result=", "% complete",
    "; freshness ", "; starting empty", "Executor", "at least ",
    "agent unavailable", "just now", "read+write", "read-only",
    "snapshot_unavailable", "tracker unavailable", "workspace:",
}
FOUR_PLUS_CONTRACT = {
    "--show-toplevel", "AIUR_DASHBOARD_PASSWORD", "BASH_ENV", "aiur_workspaces",
    "capture-pane -p -t ", "endCursor", "parent_issue_number",
    "parent_issue_repo", "subIssues", "sub_issue_number", "sub_issue_repo",
    "text/event-stream", "x-ratelimit-resource",
}
FOUR_PLUS_FIELD = {
    "agent_family", "attributes", "backends", "coverage", "head_committed_at",
    "legacy_attention", "orchestrator_unavailable", "query_source", "recommendation",
    "resolved_model", "reversibility", "source_id", "source_version",
    "unclassified", "upstream_provider", "windowDurationMins",
}
FOUR_PLUS_MIXED = {
    "[^a-z0-9]+", "analytics", "arguments", "available", "critical",
    "deferred", "in-progress", "opencode", "priority", "rate_limits",
    "reset_at", "session_id", "severity", "tool_result",
}
SAME_OWNER_CONTRACT = {
    "^[a-z][a-z0-9-]{0,63}$": "covered_by_web-occ-18_close_event_regex",
    "chatcmpl-": "source_screened_completion_id_prefix_contract",
    "cache_creation_input_tokens": "source_screened_provider_token_alias",
    "event.sequence": "source_screened_telemetry_field_contract",
    "latest_comment": "source_screened_review_thread_field_contract",
    "mergeable_state": "source_screened_takeover_alert_field_contract",
    "submitted": "source_screened_review_action_contract",
    "totalCount": "source_screened_graphql_field_contract",
}
SIGNAL_PATTERN = re.compile(
    r"version|timeout|limit|status|topic|auth|cache|quota|path|token|boundary|ttl|"
    r"credential|session|duration|ms|secret|signature|rate|poll|retry|webhook|"
    r"workspace|issue|ticket|github|executor|decision", re.I
)
SIGNAL_SAME_CONTRACT = {
    " decision=restore_pending reason=active_turn", ".agent.decision.",
    "/(?:issues|pulls)/(\\d+)(?:/|$)", "AIUR_AGENT_WORKSPACE",
    "AIUR_CLI_VERSION", "AIUR_GITHUB_BUDGET_CONSUMER", "AIUR_REPO_STATE_PATH",
    "AIUR_SESSION_TMPFILE", "All retained decisions", "Build · issue-",
    "GH_TOKEN", "Partial retained Decision data", "This Command changed to version ",
    "\\Aticket\\.([^.]+)\\.", "__github_quota_probe__",
    "decision-delivery-", "decision-lifecycle-persistence-", "executor.#",
    "executor.decision.deferred", "has not polled yet", "issue.label.added.agent.",
    "maximum agent duration reached", "near limit", "number issue_number pull_number",
    "rate_limit/update", "session max_concurrent_agents", "session:",
    "snapshot_timeout", "system.github.connectivity_lost", "ticket supply",
    "workspaceWrite", "x-github-delivery", "x-github-event", "x-poll-interval",
}
SIGNAL_DISTINCT_ROLES = {
    " status=", "--version", "GitHub returned HTTP ", "Ticket #", "Ticket: ",
    "api.github.com", "authentication failed", "rate_limit", "session_id",
    "unlimited", "unauthorized", "www.github.com", "this session",
}


def source_context(path, line):
    if "Logger." in line or "IO.puts" in line:
        return "log_or_cli_output"
    if "/config/schema/" in path or "field(" in line or "validate_" in line:
        return "config_or_validation"
    if "System.cmd" in line or "Tmux.command" in line or "GenServer.call" in line:
        return "command_or_process"
    if "Map.get" in line or "Map.fetch" in line or '" => ' in line or '["' in line:
        return "structured_field_access"
    if path.startswith("src/lib/aiur_web/"):
        return "web_or_presenter"
    if "/events/" in path or "topic" in line:
        return "event_or_topic"
    return "other_source_expression"


def owner_bucket(path):
    parts = path.split("/")
    if len(parts) < 5:
        return "/".join(parts[:4])
    return "/".join(parts[:5])


def identity(row):
    value = row["value"]
    return row["kind"], type(value).__name__, value


def select_shape(value):
    if value == "127.0.0.1":
        return "loopback_protocol_host"
    if not value.strip() or not any(c.isalpha() for c in value):
        return "nonsemantic_or_protocol_symbols"
    if value.startswith(("/", "https://", "http://", "refs/", "x-", "AIUR_")):
        return "path_url_header_or_env"
    if value.startswith((".", "pr.", "issue.", "executor.", "turn/")):
        return "topic_or_event_fragment"
    if value != value.strip() or " " in value or value[:1].isupper():
        return "display_log_sql_or_message_fragment"
    if all(c.isalnum() or c == "_" for c in value):
        return "field_identifier_or_version"
    return "other_string_fragment"


def build(census_path, selected_path, snapshot_path):
    with gzip.open(census_path, "rb") as handle:
        raw = handle.read()
    census = json.loads(raw)
    selected = json.loads(selected_path.read_text())
    assert hashlib.sha256(raw).hexdigest() == selected["input_sha256"]
    for source in census["files"]:
        path = snapshot_path / source["path"]
        assert hashlib.sha256(path.read_bytes()).hexdigest() == source["sha256"], source["path"]
    groups = collections.defaultdict(list)
    for row in census["literals"]:
        groups[identity(row)].append(row)
    selected_ids = {identity(row) for row in selected["rows"]}
    rows = []
    source_lines = {}
    for (kind, value_type, value), sites in groups.items():
        modules = {site["module"] for site in sites}
        if len(modules) < 2 or (kind, value_type, value) in selected_ids:
            continue
        anchors = []
        seen = set()
        contexts = set()
        owners = set()
        for site in sites:
            if site["module"] in seen:
                continue
            seen.add(site["module"])
            path = site["path"]
            if path not in source_lines:
                source_lines[path] = (snapshot_path / path).read_text().splitlines()
            line_no = site["line"]
            assert 1 <= line_no <= len(source_lines[path])
            contexts.add(source_context(path, source_lines[path][line_no - 1]))
            owners.add(owner_bucket(path))
            anchors.append([site["path"], site["line"], site["module"]])
            if len(anchors) == 2:
                continue
        if kind == "string":
            role = select_shape(value) if len(value) >= 8 else "short_string_symbol_or_token"
            disposition = REVIEWED_STRINGS.get(value, "unreviewed_source_semantics")
            if len(value) >= 8 and len(modules) >= 4 and disposition == "unreviewed_source_semantics":
                if value in FOUR_PLUS_TOPIC:
                    disposition = "source_screened_topic_or_event"
                elif value in FOUR_PLUS_DISPLAY:
                    disposition = "source_screened_display_or_log"
                elif value in FOUR_PLUS_CONTRACT:
                    disposition = "source_screened_protocol_or_contract"
                elif value in FOUR_PLUS_FIELD:
                    disposition = "source_screened_structured_field"
                elif value in FOUR_PLUS_MIXED:
                    disposition = "source_screened_mixed_roles"
                else:
                    raise ValueError(f"Unscreened four-plus long string: {value!r}")
            if len(value) >= 8 and len(modules) < 4 and len(owners) == 1 and disposition == "unreviewed_source_semantics":
                disposition = SAME_OWNER_CONTRACT.get(value, "source_screened_same_owner_role")
            if len(value) >= 8 and len(modules) in (2, 3) and len(owners) > 1 and SIGNAL_PATTERN.search(value) and disposition == "unreviewed_source_semantics":
                if value in SIGNAL_SAME_CONTRACT:
                    disposition = "source_screened_cross_owner_shared_contract"
                elif value in SIGNAL_DISTINCT_ROLES:
                    disposition = "source_screened_cross_owner_distinct_roles"
                else:
                    disposition = "source_screened_cross_owner_signal_role"
            if len(value) >= 8 and disposition == "unreviewed_source_semantics":
                if contexts == {"log_or_cli_output"}:
                    disposition = "source_screened_log_fragment_distinct_messages"
                elif contexts == {"command_or_process"}:
                    disposition = "source_screened_command_protocol_distinct_callers"
                elif contexts == {"event_or_topic"}:
                    disposition = "source_screened_event_topic_contract"
                elif contexts == {"web_or_presenter"}:
                    disposition = "source_screened_web_presentation_or_protocol"
        elif value_type == "int" and value in (0, 1):
            role, disposition = "generic_integer_identity", "unreviewed_source_semantics"
        elif value_type == "float" and value in (0.0, 1.0):
            role, disposition = "generic_float_identity", "unreviewed_source_semantics"
        elif value in SYNTAX_CODEPOINTS:
            role, disposition = "parser_or_character_codepoint", "source_screened_mixed_syntax"
        else:
            role = next((name for name, values in NUMBER_ROLES.items() if value in values), "numeric_role_unclassified")
            disposition = "source_screened_role_only" if role != "numeric_role_unclassified" else "unreviewed_source_semantics"
        rows.append({"kind": kind, "type": value_type, "value": value,
                     "modules": len(modules), "sites": len(sites), "role": role,
                     "disposition": disposition, "anchors": anchors[:2],
                     "contexts": sorted(contexts), "owner_relation": "one_source_owner" if len(owners) == 1 else "multiple_source_owners"})
    rows.sort(key=lambda row: (row["kind"], row["type"], str(row["value"])))
    counts = collections.Counter(row["disposition"] for row in rows)
    files = sorted({anchor[0] for row in rows for anchor in row["anchors"]})
    file_id = {path: index for index, path in enumerate(files)}
    roles = sorted({row["role"] for row in rows})
    role_id = {role: index for index, role in enumerate(roles)}
    dispositions = sorted({row["disposition"] for row in rows})
    disposition_id = {disposition: index for index, disposition in enumerate(dispositions)}
    context_names = sorted({name for row in rows for name in row["contexts"]})
    context_id = {name: index for index, name in enumerate(context_names)}
    compact_rows = [
        [row["kind"][0], row["type"][0], row["value"], row["modules"],
         row["sites"], role_id[row["role"]], disposition_id[row["disposition"]],
         [[file_id[anchor[0]], anchor[1]] for anchor in row["anchors"]],
         [context_id[name] for name in row["contexts"]],
         1 if row["owner_relation"] == "one_source_owner" else 0]
        for row in rows
    ]
    return {"status": "candidate-ledger-not-semantic-clearance",
            "snapshot": selected["snapshot"], "input_sha256": selected["input_sha256"],
            "identity": "kind + JSON numeric type + scalar value; 0 differs from 0.0",
            "row_schema": ["kind_first_letter", "type_first_letter", "value", "module_count", "site_count", "role_id", "disposition_id", "first_two_distinct_module_file_line_anchors", "source_line_context_ids", "one_source_owner_boolean"],
            "cross_module_groups": 1705, "selected_high_fanout": 191,
            "remaining_groups": len(rows),
            "remaining_long_strings": sum(r["kind"] == "string" and len(r["value"]) >= 8 for r in rows),
            "remaining_short_strings": sum(r["kind"] == "string" and len(r["value"]) < 8 for r in rows),
            "remaining_numbers": sum(r["kind"] == "number" for r in rows),
            "disposition_counts": dict(sorted(counts.items())),
            "files": files, "roles": roles, "dispositions": dispositions,
            "source_line_contexts": context_names,
            "rows": compact_rows}


if __name__ == "__main__":
    report = build(Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3]))
    assert report["remaining_groups"] == 1514
    print(json.dumps(report, ensure_ascii=False, separators=(",", ":")))
