/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WireContract = CapabilitiesReport | CapabilityError;
export type CapabilityEntry = {
  state: CapabilityState;
  reason?: CapabilityReason | null;
  depends_on?: string[];
  version?: number;
  observed_at?: string;
  route?: string;
  mode?: "in_band_hold" | "defer_resume" | "none";
  v?: number;
  retention?: unknown;
  [k: string]: unknown;
};
export type CapabilityState = "available" | "degraded" | "unavailable" | "unknown";
export type CapabilityReason =
  | "not_installed"
  | "not_configured"
  | "disabled"
  | "not_running"
  | "unsupported_tracker"
  | "executor_absent"
  | "executor_not_managed"
  | "snapshot_stale"
  | "snapshot_unpublished"
  | "instance_key_missing"
  | "instance_key_invalid"
  | "identity_unreadable"
  | "journal_corrupt"
  | "store_unavailable"
  | "writes_paused"
  | "spec_invalid"
  | "dependency_unavailable"
  | "unknown";

export interface CapabilitiesReport {
  contract: "aiur.capabilities";
  contract_version: 1;
  boot_id: string;
  revision: number;
  observed_at: string;
  age_ms: number;
  freshness: "current" | "stale";
  min_client_versions: {
    [k: string]: string;
  };
  machine: {
    machine_id: string;
    label: string;
    [k: string]: unknown;
  } | null;
  instance: {
    instance_id: string | null;
    aiur_version: string;
    run_shape: {
      http_listener: boolean;
      dashboard_pages: boolean;
      dashboard: boolean;
      headless: boolean;
      interactive_cli: boolean;
      executor_mode: boolean;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  } | null;
  repository: {
    kind: "github" | "linear" | "memory";
    owner: string | null;
    name: string;
    [k: string]: unknown;
  } | null;
  executor: {
    state: "active" | "idle" | "stalled" | "expired" | "absent" | "unknown";
    consumer_id: string | null;
    harness: string | null;
    session_ref?: {
      conversation_id: string;
      session_seq: number;
      [k: string]: unknown;
    } | null;
    [k: string]: unknown;
  } | null;
  capabilities: {
    [k: string]: CapabilityEntry;
  };
  [k: string]: unknown;
}
export interface CapabilityError {
  error: "capability_unavailable";
  capability: string;
  state: "degraded" | "unavailable" | "unknown";
  reason: CapabilityReason;
  depends_on?: string[] | null;
  revision: number;
  boot_id: string;
  [k: string]: unknown;
}
