# Existing cross-owner writes only; remove rows as responsibilities move. Never add a new writer.
[
  {Aiur.Orchestrator.Dispatcher, :auto_resume, "Dispatcher uses a temporary State copy with auto_resume cleared for admission; the live lifecycle state is unchanged."},
  {Aiur.Orchestrator.StartupClaimReconciler, :last_polled_issues,
   "Startup reconciliation refreshes last_polled_issues after releasing an orphaned claim; retain until core owns that snapshot update."},
  {Aiur.Opencode.SlotPolicy, :max_concurrent_agents, "False positive: SlotPolicy updates its own struct, whose max_concurrent_agents field shares the State name."},
  {Aiur.Orchestrator.AutoResume, :last_polled_issues, "Baseline core write in Aiur.Orchestrator.AutoResume; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.CiLifecycle, :running, "Baseline lifecycle write in Aiur.Orchestrator.CiLifecycle; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.CommentPolling, :pr_review_seen_at, "Baseline pr_lifecycle write in Aiur.Orchestrator.CommentPolling; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.CommentWake, :running, "Baseline lifecycle write in Aiur.Orchestrator.CommentWake; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :candidate_snapshot_fresh?, "Baseline core write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :ci_lifecycle, "Dispatcher stores candidate_list_cache inside ci_lifecycle.poll_cache; split this cache in the later ownership migration."},
  {Aiur.Orchestrator.Dispatcher, :claimed, "Baseline lifecycle write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :dispatch_recovery, "Baseline lifecycle write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :initial_dispatch_cycle, "Baseline core write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :model_fallback_waiting, "Baseline lifecycle write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :poll_check_in_progress, "Baseline core write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :released_claims, "Baseline lifecycle write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :retry_attempts, "Baseline lifecycle write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :running, "Baseline lifecycle write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :snapshot_ready?, "Baseline core write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :tracker_preflight_alert_resolution_emitted, "Baseline core write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Dispatcher, :tracker_preflight_alert_signature, "Baseline core write in Aiur.Orchestrator.Dispatcher; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.GithubBudgetPause, :running, "Baseline lifecycle write in Aiur.Orchestrator.GithubBudgetPause; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :active_attention_topics, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :capacity_starvation, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :capacity_starvation_resolution_emitted, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :contradictory_state_label_alert_active, "Baseline lifecycle write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :contradictory_state_label_tickets, "Baseline lifecycle write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :decision_store_unavailable_alert_active, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :decision_store_unavailable_alert_resolution_emitted,
   "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :decision_store_unavailable_since_ms, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :dependency_circular_wait, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :fleet_capacity_starvation, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :fleet_capacity_starvation_resolution_emitted, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :observed_error_alert_causes, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :observed_error_alerts, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :queue_store, "Baseline messaging write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :released_claims, "Baseline lifecycle write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.IssueSync, :todo_over_capacity_alert_active, "Baseline dispatch write in Aiur.Orchestrator.IssueSync; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Lifecycle, :max_concurrent_agents, "Baseline dispatch write in Aiur.Orchestrator.Lifecycle; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Lifecycle, :next_poll_due_at_ms, "Lifecycle maintains existing poll cadence and queued-demand state; note_queued_demand/1 is the sanctioned RC-19 hook."},
  {Aiur.Orchestrator.Lifecycle, :poll_check_in_progress, "Lifecycle maintains existing poll cadence and queued-demand state; note_queued_demand/1 is the sanctioned RC-19 hook."},
  {Aiur.Orchestrator.Lifecycle, :poll_interval_ms, "Lifecycle maintains existing poll cadence and queued-demand state; note_queued_demand/1 is the sanctioned RC-19 hook."},
  {Aiur.Orchestrator.Lifecycle, :queued_demand_hints, "Lifecycle maintains existing poll cadence and queued-demand state; note_queued_demand/1 is the sanctioned RC-19 hook."},
  {Aiur.Orchestrator.Lifecycle, :tick_timer_ref, "Lifecycle maintains existing poll cadence and queued-demand state; note_queued_demand/1 is the sanctioned RC-19 hook."},
  {Aiur.Orchestrator.Lifecycle, :tick_token, "Lifecycle maintains existing poll cadence and queued-demand state; note_queued_demand/1 is the sanctioned RC-19 hook."},
  {Aiur.Orchestrator.LifecycleFence, :running, "Baseline lifecycle write in Aiur.Orchestrator.LifecycleFence; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.OperatorMessages, :running, "Baseline lifecycle write in Aiur.Orchestrator.OperatorMessages; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PauseResume, :claimed, "Baseline lifecycle write in Aiur.Orchestrator.PauseResume; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PauseResume, :last_polled_issues, "Baseline core write in Aiur.Orchestrator.PauseResume; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PauseResume, :retry_attempts, "Baseline lifecycle write in Aiur.Orchestrator.PauseResume; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PauseResume, :running, "Baseline lifecycle write in Aiur.Orchestrator.PauseResume; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PriorityControl, :last_polled_issues, "Baseline core write in Aiur.Orchestrator.PriorityControl; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PriorityControl, :retry_attempts, "Baseline lifecycle write in Aiur.Orchestrator.PriorityControl; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PriorityControl, :running, "Baseline lifecycle write in Aiur.Orchestrator.PriorityControl; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.PushRouting, :running, "Baseline lifecycle write in Aiur.Orchestrator.PushRouting; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RateLimitFallback, :running, "Baseline lifecycle write in Aiur.Orchestrator.RateLimitFallback; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.Reconciler, :running_issue_cache, "Baseline core write in Aiur.Orchestrator.Reconciler; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RemoteControlMode, :retry_attempts, "Baseline lifecycle write in Aiur.Orchestrator.RemoteControlMode; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RemoteControlMode, :running, "Baseline lifecycle write in Aiur.Orchestrator.RemoteControlMode; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RetryEngine, :control_lifecycle, "Baseline control write in Aiur.Orchestrator.RetryEngine; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RetryEngine, :observed_error_alert_causes, "Baseline dispatch write in Aiur.Orchestrator.RetryEngine; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RetryEngine, :observed_error_alerts, "Baseline dispatch write in Aiur.Orchestrator.RetryEngine; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RetryEngine, :queue_store, "Baseline messaging write in Aiur.Orchestrator.RetryEngine; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.RuntimeWatchdog, :running, "Baseline lifecycle write in Aiur.Orchestrator.RuntimeWatchdog; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.SnapshotStore, :globally_paused, "Baseline control write in Aiur.Orchestrator.SnapshotStore; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.State, :rework_attempt_alerted, "Baseline pr_lifecycle write in Aiur.Orchestrator.State; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.State, :rework_attempts, "Baseline pr_lifecycle write in Aiur.Orchestrator.State; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.State, :running, "Baseline lifecycle write in Aiur.Orchestrator.State; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.StatusReport, :waiting_for_human_episodes, "Baseline core write in Aiur.Orchestrator.StatusReport; retain until this responsibility moves to its field owner."},
  {Aiur.Orchestrator.TokenAccounting, :running, "Baseline lifecycle write in Aiur.Orchestrator.TokenAccounting; retain until this responsibility moves to its field owner."}
]
