defmodule Aiur.Codex.SkillBridge do
  @moduledoc """
  Prepares shared Aiur skills for Codex discovery.

  The repository keeps shared Aiur skill text under `.claude/skills` and tracks
  `.codex/skills/<name>` as symlinks to those canonical directories. Some Codex
  skill-discovery paths do not descend into top-level symlinked directories, so
  a live workspace needs real `.codex/skills/<name>` directories with real
  files generated from the canonical `.claude/skills` source.
  """

  require Logger

  @marker ".aiur-skill-bridge"

  @doc """
  Materialize Codex-visible directories for any `.codex/skills/*` symlink that
  points into `.claude/skills`.

  In git workspaces, tracked top-level symlink paths are marked skip-worktree
  first so replacing them with generated directories does not dirty every agent
  run.
  """
  @spec materialize_shared_skills(Path.t()) :: :ok | {:error, term()}
  def materialize_shared_skills(workspace) when is_binary(workspace) do
    workspace = Path.expand(workspace)
    codex_skills_root = Path.join([workspace, ".codex", "skills"])
    claude_skills_root = Path.join([workspace, ".claude", "skills"])

    case shared_skill_targets(codex_skills_root, claude_skills_root) do
      {:ok, targets} -> materialize_targets(workspace, targets)
      :skip -> :ok
      {:error, reason} -> {:error, {:list_codex_skills_failed, reason}}
    end
  end

  def materialize_shared_skills(_workspace), do: :ok

  defp shared_skill_targets(codex_skills_root, claude_skills_root) do
    cond do
      not File.dir?(codex_skills_root) ->
        :skip

      not File.dir?(claude_skills_root) ->
        :skip

      true ->
        codex_skills_root
        |> File.ls()
        |> codex_skill_targets(codex_skills_root, claude_skills_root)
    end
  end

  defp codex_skill_targets({:error, reason}, _codex_skills_root, _claude_skills_root) do
    {:error, reason}
  end

  defp codex_skill_targets({:ok, entries}, codex_skills_root, claude_skills_root) do
    targets =
      entries
      |> Enum.sort()
      |> Enum.flat_map(fn entry ->
        codex_skill_path = Path.join(codex_skills_root, entry)

        case shared_skill_target(codex_skill_path, codex_skills_root, claude_skills_root) do
          {:ok, claude_skill_path} -> [{codex_skill_path, claude_skill_path}]
          :skip -> []
        end
      end)

    {:ok, targets}
  end

  defp materialize_targets(workspace, targets) do
    Enum.reduce_while(targets, :ok, fn {codex_skill_path, claude_skill_path}, :ok ->
      case materialize_skill(workspace, codex_skill_path, claude_skill_path) do
        :ok -> {:cont, :ok}
        {:error, reason} -> {:halt, {:error, reason}}
      end
    end)
  end

  defp shared_skill_target(codex_skill_path, codex_skills_root, claude_skills_root) do
    case File.lstat(codex_skill_path) do
      {:ok, %File.Stat{type: :symlink}} ->
        case File.read_link(codex_skill_path) do
          {:ok, link_target} ->
            link_target
            |> Path.expand(codex_skills_root)
            |> shared_skill_target_or_skip(claude_skills_root)

          _ ->
            :skip
        end

      {:ok, %File.Stat{type: :directory}} ->
        if File.exists?(Path.join(codex_skill_path, @marker)) do
          codex_skill_path
          |> Path.basename()
          |> then(&Path.join(claude_skills_root, &1))
          |> shared_skill_target_or_skip(claude_skills_root)
        else
          :skip
        end

      _ ->
        :skip
    end
  end

  defp shared_skill_target_or_skip(claude_skill_path, claude_skills_root) do
    if shared_skill_target?(claude_skill_path, claude_skills_root) do
      {:ok, claude_skill_path}
    else
      :skip
    end
  end

  defp shared_skill_target?(claude_skill_path, claude_skills_root) do
    File.dir?(claude_skill_path) and
      File.exists?(Path.join(claude_skill_path, "SKILL.md")) and
      String.starts_with?(claude_skill_path <> "/", claude_skills_root <> "/")
  end

  defp materialize_skill(workspace, codex_skill_path, claude_skill_path) do
    relpath = Path.relative_to(codex_skill_path, workspace)

    with :ok <- maybe_mark_skip_worktree(workspace, relpath),
         :ok <- remove_existing_codex_skill_path(codex_skill_path),
         :ok <- File.mkdir_p(codex_skill_path),
         :ok <- File.write(Path.join(codex_skill_path, @marker), "generated by Aiur.Codex.SkillBridge\n"),
         :ok <- copy_skill_files(codex_skill_path, claude_skill_path) do
      Logger.debug("Materialized Codex skill #{relpath} from #{Path.relative_to(claude_skill_path, workspace)}")
      :ok
    else
      {:error, reason} -> {:error, {:materialize_codex_skill_failed, relpath, reason}}
    end
  end

  defp remove_existing_codex_skill_path(path) do
    case File.lstat(path) do
      {:ok, %File.Stat{type: :directory}} ->
        case File.rm_rf(path) do
          {:ok, _paths} -> :ok
          {:error, reason, failed_path} -> {:error, {:rm_rf_failed, failed_path, reason}}
        end

      {:ok, _stat} ->
        File.rm(path)

      {:error, :enoent} ->
        :ok

      {:error, reason} ->
        {:error, reason}
    end
  end

  defp maybe_mark_skip_worktree(workspace, relpath) do
    if git_workspace?(workspace) and git_tracked?(workspace, relpath) do
      case System.cmd("git", ["update-index", "--skip-worktree", "--", relpath],
             cd: workspace,
             stderr_to_stdout: true
           ) do
        {_output, 0} -> :ok
        {output, status} -> {:error, {:git_skip_worktree_failed, status, String.trim(output)}}
      end
    else
      :ok
    end
  end

  defp git_workspace?(workspace) do
    File.exists?(Path.join(workspace, ".git"))
  end

  defp git_tracked?(workspace, relpath) do
    case System.cmd("git", ["ls-files", "--error-unmatch", "--", relpath],
           cd: workspace,
           stderr_to_stdout: true
         ) do
      {_output, 0} -> true
      {_output, _status} -> false
    end
  rescue
    ErlangError -> false
  end

  defp copy_skill_files(codex_skill_path, claude_skill_path) do
    claude_skill_path
    |> skill_files()
    |> Enum.reduce_while(:ok, fn source_file, :ok ->
      relative = Path.relative_to(source_file, claude_skill_path)
      dest = Path.join(codex_skill_path, relative)

      with :ok <- File.mkdir_p(Path.dirname(dest)),
           :ok <- File.cp(source_file, dest),
           :ok <- copy_mode(source_file, dest) do
        {:cont, :ok}
      else
        {:error, reason} -> {:halt, {:error, {:copy_skill_file_failed, relative, reason}}}
      end
    end)
  end

  defp copy_mode(source_file, dest) do
    case File.stat(source_file) do
      {:ok, %File.Stat{mode: mode}} -> File.chmod(dest, mode)
      {:error, reason} -> {:error, reason}
    end
  end

  defp skill_files(claude_skill_path) do
    claude_skill_path
    |> Path.join("**/*")
    |> Path.wildcard()
    |> Enum.filter(&File.regular?/1)
    |> Enum.sort()
  end
end
